[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "FeralCompany"
name = "FeralBright"
description = "A simple plugin with various methods of lighting up the facility"
websiteUrl = "https://github.com/FeralCompany"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
FeralCompany-FeralCommon = "0.1.0"
AinaVT-LethalConfig = "1.4.1"
Rune580-LethalCompany_InputUtils = "0.7.4"

[build]
icon = "icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../bin/netstandard2.1/FeralBright.dll"
target = "BepInEx/plugins/FeralBright.dll"

[[build.copy]]
source = "../CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "../LICENSE"
target = "LICENSE"

[publish]
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["bepinex", "mods", "clientside", "misc"]
